Add now function
gsk-aiops/bellman pull request #461
Opened 2021-06-29 16:07 UTC by JuanMGN

Add support to now function according the specification:
https://www.w3.org/TR/sparql11-query/#func-now

2021-07-01 14:56 UTC, patofp reviewed
With the introduction of Evaluation we should think about adapting the rest of the tests to that same formula, if I'm not mistaken it would apply at least to function suites where a projection is normally used. This way test are as homogeneous as they can be across all the project. What are your thoughts?

2021-07-01 14:56 UTC, patofp commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/package.scala
> +        case Left(e)  => throw new Exception(e.toString)
Maybe instead of throwing a exception we can fail with something like:
`fail("I've got a bad feeling about this.")` or something similar: https://www.scalatest.org/user_guide/using_assertions

2021-07-01 15:24 UTC, pepegar requested changes

2021-07-01 15:24 UTC, pepegar commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/package.scala
> +    def eval(
Can you add docs here explaining how should it be used?

2021-07-01 15:24 UTC, pepegar commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateParser.scala
> +object DateParser {
What do you think about renaming this to `DateTimeFuncsParser` or somethign like thatt? now it seems like it parses dates

2021-07-01 15:24 UTC, pepegar commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
> +object Date {
Same here, `DateTimeFunc` maybe?

2021-07-02 09:55 UTC, patofp approved these changes
LGTM!

2021-07-02 10:17 UTC, JuanMGN commented
As Patricio says, I think adapting all the tests to this same formula is a good idea, if possible. Maybe, when Pepe finishes the ticket to improve the test time or during it.

2021-07-02 10:41 UTC, pepegar approved these changes

2021-07-02 11:41 UTC, merged