Add strlang function
gsk-aiops/bellman pull request #475
Opened 2021-07-07 17:38 UTC by puremachinery

Adding support for the STRLANG function. https://www.w3.org/TR/sparql11-query/#func-strlang

Closes #265

2021-07-08 16:47 UTC, puremachinery commented
It looks like the check is failing on a linter warning for the BuiltInFuncParser now having over 70 methods? Shall I refactor BuiltInFuncParser, e.g. maybe pull abs/ceil/round/etc into a MathFuncParser?

2021-07-09 07:15 UTC, patofp commented
> It looks like the check is failing on a linter warning for the BuiltInFuncParser now having over 70 methods? Shall I refactor BuiltInFuncParser, e.g. maybe pull abs/ceil/round/etc into a MathFuncParser?

This is because scalastyle configuration, this is set here and can be modified:
https://github.com/gsk-aiops/bellman/blob/ea09e8a28e25ee530dacb306338984b0eb6a45b1/scalastyle-config.xml#L104

Said that, I think it is a good practice to keep things small, clear and modularized, so I think it is a good idea to split parsers into small ones, it makes them more human readable. 😆 

By the way, there is also a way turn off this style checks on particular code:

```
// scalastyle:off
...
// naughty stuff
...
// scalastyle:on
```

or:

`naughty()  // scalastyle:ignore`

[Scalastyle doc](http://www.scalastyle.org/configuration.html)

> I'll try that for now. (I also see the other warning about the Algebra, adding fix to QueryExtractor.)

Cool, whenever it is possible we try to be exhaustive in our pattern matchings. 😉

2021-07-09 07:35 UTC, patofp requested changes
Just a couple of things to change on the tests, for the rest LGTM!

2021-07-09 07:35 UTC, patofp commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrlangSpec.scala
> +    print(query)
I think it is better not necessary to print things on test.

2021-07-09 07:35 UTC, patofp commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrlangSpec.scala
> +      .compile(df, query, config) match {
Here on tests we usually call the unsafe method `.right.get` on this Either, it will throw that exception. Although the correct way would be to instead of throwing that exception we would fail the test.

```
...
case Left(l) => fail(l.toString)
...
```

2021-07-09 09:36 UTC, pepegar approved these changes
Looks good to me!

2021-07-09 09:36 UTC, pepegar commented on modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
> +      case MathFunc.FLOOR(s)                           => FLOOR(s)
👍🏻

2021-07-09 14:11 UTC, puremachinery commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrlangSpec.scala
> +    print(query)
Ah yes, did this while trying to verify something, but didn't mean to check it in.

2021-07-09 14:11 UTC, puremachinery commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrlangSpec.scala
> +      .compile(df, query, config) match {
Same as other comment, this was just for debugging, not meant to check in. Thanks.

2021-07-09 14:15 UTC, puremachinery commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrlangSpec.scala
> +      .compile(df, query, config) match {
Removed.

2021-07-09 14:15 UTC, puremachinery commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrlangSpec.scala
> +    print(query)
Removed.

2021-07-09 14:29 UTC, patofp approved these changes
LGTM!

2021-07-09 17:15 UTC, merged