Add bnode function
gsk-aiops/bellman pull request #534
Opened 2021-09-03 16:28 UTC by TomyMeren

# Description

Implementation of the BNODE function
https://www.w3.org/TR/sparql11-query/#func-bnode

## Type of change

enhacement

2021-09-06 08:01 UTC, patofp requested changes

2021-09-06 09:01 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
> +    val udfFoo = udf(nameToArrayOfBits)
I have not excuse 😅

2021-09-06 09:01 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
> +  /** @param col
I have not excuse again😅

2021-09-06 09:30 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
> +    // Necesary var to generate diferents UUIDS between rows names when you specific de label name
The think is that we need to generates differents UUID per row. 

When you don't specific a input parameter, the function use UUID.randomUUID(). and everything is ok.

When you specific a Input parameter we use UUID.nameUUIDFromBytes(value:Array[Bytes]) you can specific a array of bytes(witch we get from the string input parameter) and generates the same UUID if you specific the same name. So far so good. The problem is that you need one specific and different UUID per row and you need replicate the same UUIDs per row for the same name.

I think that if we forget the pure functional part It isn't a bad solutions. I have doubts with its behaviour in a distributed cluster. But I per node generates his own part of BNODEs all will be fine.

In any case I will try to change to a specific alternative 😉

2021-09-06 10:36 UTC, pepegar requested changes
Great job @TomyMeren , here are a couple of comments I think we should review.

2021-09-06 10:36 UTC, pepegar commented on modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
> +    // Necesary var to generate diferents UUIDS between rows names when you specific de label name
I think we need to rethink this.

The way I understand the [spec](https://www.w3.org/TR/sparql11-query/#func-bnode), we should generate:

1. random values for each time the `bnode()` function is called without params.  That part we're doing it in the `if` statement. ✅ 
2. a random value for each different literal passed to the `bnode(literal)` function.  What you're doing here is adding an extra string to the `literal` input of the function, effectively changing the value of the result.  I think we shouldn't do that, but instead leave the input as input to `nameUUIDFromBytes`, right?

If you want we can discuss it further.

2021-09-06 10:36 UTC, pepegar commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/BNodeSpec.scala
> +        )
In this test, I'd also test that all values of the resulting column are equal

2021-09-06 10:36 UTC, pepegar commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
> +      .map(f => BNODE(f))
👍🏻

2021-09-06 10:36 UTC, pepegar commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
> +      s: Expression = StringVal.STRING("")
how do you feel about changing the type of this to `Option[Expression]`?  I think it will be easier to compare stuff with `None` down the line than comparing it to an empty string.

Also, if the caller actually passes a `""`, since it's a valid literal, all generated UUIDs should be equal.

2021-09-06 11:43 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
> +    // Necesary var to generate diferents UUIDS between rows names when you specific de label name
That is like I did my first version of the function. This solutions looked fin, with the same tab name I can build de same Blank node name. 
The problem is that If you do that all the rows have the same value. I saw a different behaviour in the sprawl end point.


Please try this Query

2021-09-06 11:56 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/BNodeSpec.scala
> +        )
In which cases could  the results be equals?

If you speak about the case when create two blank nodes with the same input name, that test are in the line 270. 🙂

2021-09-06 12:06 UTC, TomyMeren commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
> +      s: Expression = StringVal.STRING("")
Yeah It is a good Idea. I use the "" because that is how It has been used In the FuncStrings.replace function.

Is the parser ready for Option input?

2021-09-08 15:40 UTC, patofp commented on modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
> +//  def bNode(maybeString: Option[String]): Column =
This code should be deleted.

2021-09-08 15:40 UTC, patofp commented on modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
> +        case BNODE(s) =>
Just like a note, when you are going to retrieve what is inside the Some() or something else, it is normal to use:
`s.getOrElse(Set.empty[VARIABE])`, instead of the pattern matching.

2021-09-08 15:40 UTC, patofp commented on modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
> +            s match {
Also in this case when there are simple computations on the Some and on the None cases, you can do:

```
s.map(si => Node("BNODE", Stream(si)).getOrElse(Leaf(BNODE"))
```

It is equivalent to the pattern matching you are doing, but it is up to you.
IMHO I try to avoid pattern matching whenever it is possible and if it doesn't affect readability.

2021-09-08 15:40 UTC, patofp commented on modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
> +        s match {
Same here, you can do:

`s.map(si => s"(bnode $si")).getOrElse("(bnode)")`

2021-10-05 09:38 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
> +//  def bNode(maybeString: Option[String]): Column =
Done!

2021-10-05 09:49 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
> +        case BNODE(s) =>
Yeah I knew that :sweat_smile: .

2021-10-05 13:39 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
> +            s match {
Done!

2021-10-05 13:51 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
> +        s match {
Done!

2021-10-05 14:49 UTC, closed without merging