We create the TableJoin and change engine.EvaluateJoin to detect when…
gsk-aiops/bellman pull request #625
Opened 2021-12-17 17:08 UTC by TomyMeren

# Description

Queries with VALUES statement can accept UNDEF on the inline data. E.g:

```
PREFIX dc:   <http://purl.org/dc/elements/1.1/> 
PREFIX :     <http://example.org/book/> 
PREFIX ns:   <http://example.org/ns#> 

SELECT ?book ?title ?price
{
   ?book dc:title ?title ;
         ns:price ?price .
   VALUES (?book ?title)
   { (UNDEF "SPARQL Tutorial")
     (:book2 UNDEF)
   }
}
```

The algebra generated for this query is:

```
(project (?book ?title ?price)
  (join
    (bgp
      (triple ?book <http://purl.org/dc/elements/1.1/title> ?title)
      (triple ?book <http://example.org/ns#price> ?price)
    )
    (table (vars ?book ?title)
      (row [?title "SPARQL Tutorial"])
      (row [?book <http://example.org/book/book2>])
    )))
```
The problem with this and similar queries is that some rows in the table part don't have all the vars values defined. For example in this Algebra the first rows don't have "?book" and the second one don't have "?title" defined.

That generates "nulls" values in the join, the normal join doesn't cross the nulls values and we lose it.

To solve this, we create a new type of join, the "tablejoin" that crosses nulls values. To apply it, we first detect this situation in the optimisation part and change the "join" to "tablejoin" in the algebra part.

2021-12-17 17:11 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
> -
We were not using  this two methods

2021-12-17 17:13 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/GraphSpec.scala
This test fail with changes and a todo say It isn't validated so I ignore it. 
Make sense?

2021-12-17 17:15 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ValuesSpec.scala
Sorry for the mess. I'm not deleting any test, I've just added new ones.

2021-12-17 17:16 UTC, patofp requested changes
Much better now! But I still think it could be simplified a little more.

I can see that methods:
`join` and `tableJoin` are very similar
`innerJoinWithGraphsColumn` and `tableJoinWithGraphsColums` also.

So maybe a flag can be passed from the evaluateJoin to the `innerJoinWithGraphsColumns`

I think that would remove a lot of duplicated code. What are your thoughts?

2021-12-17 17:55 UTC, TomyMeren commented
Yeah, done in a new commit!

2021-12-17 18:04 UTC, patofp commented
> Yeah, done in a new commit!

Nice work! Now it looks much simpler that initially.

2021-12-22 10:30 UTC, pepegar approved these changes
LGTM!

2021-12-22 10:30 UTC, pepegar commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/GraphSpec.scala
> +        )
👍🏻

2021-12-23 08:12 UTC, patofp approved these changes
LGTM!

2021-12-23 08:26 UTC, merged