Fix nulls in join
gsk-aiops/bellman pull request #634
Opened 2021-12-30 10:05 UTC by TomyMeren

# Description

It takes into account when we have null values on the left, right or both sides of the Join.

SparqQL always tries to get a value from a join hand instead of a null. This approach includes a possible combination of the fields

## Type of change

Make sure you add the correct label for the PR:

- `enhacement` if this PR adds a new feature
- `bug` if it fixes a bug
- `documentation` if it adds docs
- `breaking-change` if this PR introduces a breaking change
- `dependency-updates` if it updates dependencies

2021-12-30 13:11 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ConstructSpec.scala
> +      val result = Compiler.compile(df, None, query, config)
@patofp can you help me check this result? I have a strange result in Jena

2021-12-30 13:12 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/GraphSpec.scala
> +          Row(
this is the test with which we detected the problem

2022-01-03 08:41 UTC, patofp requested changes

2022-01-03 08:41 UTC, patofp commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ConstructSpec.scala
> +      val result = Compiler.compile(df, None, query, config)
I've checked the result on Jena and the result matches the previous version:

```
Set(
        Row(
          "_:test",
          "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>",
          "<http://id.gsk.com/dm/1.0/Document>"
        ),
        Row(
          "_:test",
          "<http://id.gsk.com/dm/1.0/docSource>",
          "\"source\""
        )
```

2022-01-03 12:15 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ConstructSpec.scala
> +      val result = Compiler.compile(df, None, query, config)
Resolved! Thank you @patofp.
It turns out that when a row have all the columns of the join condition null, they never cross.
I solved with a filter to remove those rows before the join.

2022-01-04 08:53 UTC, patofp commented on modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
> +  def innerJoinEmptyValues(
I suggest to document this method, what it does and what are the steps. What do you think?

2022-01-04 10:20 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
> +  def innerJoinEmptyValues(
Yes, sounds good!

2022-01-05 08:21 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
> +  def innerJoinEmptyValues(
Done!

2022-01-05 08:24 UTC, patofp approved these changes
LGTM! GJ!

2022-01-05 08:24 UTC, patofp commented on modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
> +  /** Check if the df's have nulls values in any of his rows. if don't have, we
Nice!

2022-01-05 08:55 UTC, merged