Broken rdf testing
gsk-aiops/bellman pull request #686
Opened 2022-04-22 15:34 UTC by TomyMeren

# Description

## Type of change

Make sure you add the correct label for the PR:

- `enhacement` if this PR adds a new feature
- `bug` if it fixes a bug
- `documentation` if it adds docs
- `breaking-change` if this PR introduces a breaking change
- `dependency-updates` if it updates dependencies

2022-04-22 18:28 UTC, L-Lavigne commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
Is this timeout a performance issue in Bellman? If so let's create a ticket to address it and put a TODO there.

2022-04-22 18:28 UTC, L-Lavigne commented on rdf-test-results.md
> +|**Success**|       8       |    30    |
Nice! 👏 

Do you know why the total number of tests has gone down so much? Change in the online test suite contents, or commenting out of `property-path/manifest.ttl` ?

2022-04-22 19:40 UTC, TomyMeren commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
On my local machine it looks like a timeout but I've run it with and action and it's a java.lang.OutOfMemoryError: Java heap space

Here is the full error:

https://github.com/gsk-aiops/bellman/runs/6133214990?check_suite_focus=true

It doesn't look like a performance issue in Belmam, but I put a TODO to check when we go to do the full review of the rdf test

2022-04-22 19:48 UTC, TomyMeren commented on rdf-test-results.md
> +|**Success**|       8       |    30    |
Sorry, I had not updated the report. :sweat_smile:

The “Run RDF test" has worked on the accion:
https://github.com/gsk-aiops/bellman/actions/runs/2209578543
I guess the error is from running it manually

2022-04-25 04:51 UTC, L-Lavigne commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
Before ignoring this test, could we try a few more things to fix the error? When googling the logged warning "Broadcasting large task binary" I find answers related to partition sizes like this one, might be worth a try: https://stackoverflow.com/questions/28878654/spark-using-python-how-to-resolve-stage-x-contains-a-task-of-very-large-size-x

2022-04-26 18:08 UTC, TomyMeren commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
I have found the source of the error but I can't understand the problem. Maybe @patofp can.
The problem is not an error in the input data partition because the input data only has 11 triples.

I first saw that it didn't affect all tests so I took the first one that crashes the test to study it. The problem is not with the query, as other tests use the same query with good results, so the problem is with the input data.

Basically the error occurs when we have a reciprocal relationship of people who know each other, in the input data and the predicate is <http://xmlns.org/foaf/0.1/knows> instead of <http://xmlns.com/foaf/0.1/knows>.

2022-04-26 18:12 UTC, TomyMeren commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
So for the same query:

PREFIX : <http://example.org/>
PREFIX foaf: <http://xmlns.org/foaf/0.1/>
SELECT *
WHERE { ?X foaf:knows* ?Y }
ORDER BY ?X ?Y

With that df works:

 val df = List(
            ("<http://example.org/a>", "<http://xmlns.org/foaf/0.1/knows>", "<http://example.org/b>"),
            ("<http://example.org/b>", "<http://xmlns.org/foaf/0.1/knows>", "<http://example.org/c>")
          ).toDF("s", "p", "o")

but with this it is blocked:

val df = List(
            ("<http://example.org/a>", "<http://xmlns.com/foaf/0.1/knows>", "<http://example.org/b>"),
            ("<http://example.org/b>", "<http://xmlns.com/foaf/0.1/knows>", "<http://example.org/c>")
          ).toDF("s", "p", "o")

Obviously changing the foaf definition also in the query

2022-04-26 18:25 UTC, L-Lavigne commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
That's weird. 🤔 Just curious, any reason why we sometimes use `xmlns.org` instead of `xmlns.com` in our tests and examples? A quick google search shows that only `xmlns.com` should be valid.

2022-04-26 19:55 UTC, TomyMeren commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
I have changed my conclusion after a review, please read the comments again if you have already done so.

2022-04-26 23:44 UTC, L-Lavigne commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
Thanks for the update, in your edited comment I see 3 examples now, are you sure the first one works? I would assume that the first 2 would fail, since they both have a "knows" cycle. Can you confirm?

2022-04-27 00:29 UTC, L-Lavigne commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
I assume our actual data, including the RDF-test data, has the full namespaces and not "foaf:knows", correct? If so, does the bug with cyclic "knows" only happen when using a prefix in the query? In other words, if you use the full namespace in your query, does it work with cyclic data?

2022-04-27 06:50 UTC, patofp commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
Just to give some insight about property paths. The current implementation of property paths is based on a BFS implementation with Dataframes expanding all the nodes of the graphs to search for the paths that match the query by depth levels (path 0 - > pat 1 -> path 2 -> path n). This implementation has basically two problems.

The first one has to do with performance, expanding a graph to search for paths is very costly in time and space as it has to keep track of explored paths on an auxiliary Dataframe. We can have some discussion about this particular issue this Friday and see the details of the implementation and search for improvements.

The other one has to do with graph cycles, if our data has cycles (KG is a DG but not a DAG) then it can keep creating new paths in a loop, currently the only cycle protection we have is a hard limit that is hard coded. Without deeper analysis and based on the comments, **I think this could be the issue that is affecting**.

This is a cycle in the input dataframe:
```
val df = List(
("http://example.org/a", "foaf:knows", "http://example.org/b"),
("http://example.org/b", "foaf:knows", "http://example.org/a")
).toDF("s", "p", "o")
```

There is a posible alternative implementation for property paths that may be worth to explore [Spark GraphFrames](https://graphframes.github.io/graphframes/docs/_site/index.html), my suggestion is to do a **Property Paths GraphFrame PoC** to see if some of the issues can be solved and if it has other drawbacks as well.

Said that, right now I don't think there is a priority on addressing this known issues, leaving it on behalf of the end user to make a responsable use of property paths.

So IMHO I think that addressing this issue is not a trivial thing that we can do in the scope of this task and should be addressed separately.

Hope this insight helps to take a decision! 😉

2022-04-27 08:35 UTC, TomyMeren commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
@L-Lavigne The rdf-test uses a ttl file like this:

@prefix : <http://example.org/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

:a foaf:knows :b .
:b foaf:knows :c .

The predicate is define by a "prefix" but the file has the @prefix information to write the data with the full namespace and that is what it does when creating the Dataframe. In conclusion the input Dataframe into the rdf-test always have the full namespace.

For me define the data with prefix in the input Dataframes in any of the unit test is and error because the change to full name occurs earlier and it is not able to match these short predicates with the predicates of the query.

Another point. The bug happens regardless of whether you define the prefix in the query or you write the predicates with the full namespace, does not affect. With this data and this query also fails:

val df = List(
("http://example.org/a", "http://xmlns.com/foaf/0.1/knows", "http://example.org/b"),
("http://example.org/b", "http://xmlns.com/foaf/0.1/knows", "http://example.org/a")
).toDF("s", "p", "o")

PREFIX : <http://example.org/>
SELECT *
WHERE { ?X <http://xmlns.org/foaf/0.1/knows>* ?Y }
ORDER BY ?X ?Y

In any case, I'm with @patofp  that it isn't a priority now.
I think that that we can merge this changes to get a higher percentage into the RDF-test report and create an issue to solve this later.

2022-04-27 09:30 UTC, L-Lavigne commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
Thanks @patofp and @TomyMeren for the detailed clarification. I agree with making the cyclic bug a separate issue so we can move this current PR forward. 

I do think that lack of support for cycles would qualify as a bug since:

a) relationships such as "knows" have cycles in real-world applications;
b) the RDF tests that are failing are testing for cycles specifically (see the test names);
c) libraries such as Jena support them explicitly (search for "cycles" in https://jena.apache.org/documentation/query/property_paths.html).

@TomyMeren if you agree, could you create a new issue, quote some of our discussions above for context, and replace the "OutOfMemoryError" comment in this PR with a TODO link to the new issue? Thanks!

2022-04-27 10:04 UTC, patofp commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
> I do think that lack of support for cycles would qualify as a bug since:

Indeed @L-Lavigne. Here is the actual hard limit cycle protection if you guys want to take a look at: https://github.com/gsk-aiops/bellman/blob/c7b906ed371517091a5f8e9da78305f1336220f3/modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala#L97

2022-04-27 10:36 UTC, TomyMeren commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //time out error
https://github.com/gsk-aiops/bellman/issues/691

2022-04-27 11:22 UTC, L-Lavigne approved these changes
Thanks @TomyMeren and @patofp for your analysis of the property-paths issue!

I see the build breaks on the recently-updated microsite task though: https://github.com/gsk-aiops/bellman/runs/6191967760?check_suite_focus=true#step:10:35

I have the same issue in a PR of my own. Let's take a look, I'll be back tomorrow morning.

2022-04-28 14:26 UTC, patofp requested changes

2022-04-28 14:26 UTC, patofp commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +    //"property-path/manifest.ttl", //Todo: https://github.com/gsk-aiops/bellman/issues/691
Usually we use TODO in upper case letters.

2022-04-28 14:26 UTC, patofp commented on modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
> +          val s = sO.getOrElse("")
Try using meaningful variable names

2022-05-04 08:20 UTC, L-Lavigne commented
@patofp Have your requested changes been satisfied for this PR and if so, could you approve? Thanks!

2022-05-04 08:26 UTC, patofp approved these changes
LGTM!

2022-05-04 09:14 UTC, merged