Construct improved perfomance
gsk-aiops/bellman pull request #745
Opened 2022-07-27 11:00 UTC by TomyMeren

# Description
Changes the first approach to the evaluation of the CONSTRUCT clause.
This first approach consisted of applying a flatMap to the result of the DataFrame generated after evaluating the WHERE part of the query. This required working with the DataFrame as an RDD making it perform poorly and difficult to paralyse.

The new implementation use un-pivot and Union, two Spark SQL methods.

This are examples of times in some queries of the Perfomance test and others. Everything has been run with a single table approach (/hudi_perf_v8) and hudi: 0.10.1

Best with First approach - Bellman: 2.0.0+166-7ddf6580-SNAPSHOT
  - doc_base => 356325 ms
  - mmk => 438292 ms
  - Adapted GeneCards => 5 min

New approach- Bellman: 2.0.0+170-d40b8ab5-SNAPSHOT
- doc_base => 317582 ms
- mmk => 369996 ms
- Adapted GeneCards=> 2 min

## Type of change

Make sure you add the correct label for the PR:

- `breaking-change` if this PR introduces a breaking change
- `enhancement` if it adds a new feature
- `bug` if it fixes a bug
- `test` if it adds or updates tests
- `documentation` if it adds or updates documentation
- `dependency-update` if it updates dependencies

2022-07-28 21:41 UTC, L-Lavigne requested changes
Good work, I have some suggested changes but the main one is in the construction of the `stack` expression: removing usage of `indexOf` on a list that's not certain to be an `IndexedSeq`, and clarifying the value names.

2022-07-28 21:41 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +        accDF.union(dfKey)
```suggestion
      (accSpoDF: DataFrame, s: StringVal) =>
        val poList: List[(StringVal, StringVal)] = templateValues(s)

        val stackExpr: String =
          (poList.length +: poList.indices.flatMap(i => List(s"p$i", s"o$i")))
            .mkString("stack(", ", ", ") as (p, o)")

        val poDF: DataFrame = poList.zipWithIndex.foldLeft(dfPRev) {
          (accPoDF: DataFrame, po_i: ((StringVal, StringVal), Int)) =>
            val ((p, o), i) = po_i
            accPoDF
              .withColumn(
                s"p$i",
                stringValToColumn(p)
              )
              .withColumn(
                s"o$i",
                stringValToColumn(o)
              )
        }

        val spoDF: DataFrame = poDF
          .withColumn("s", stringValToColumn(s))
          .select(col("s"), expr(stackExpr))
          .distinct

        accSpoDF.union(spoDF)
```

2022-07-28 21:41 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +    // in normal querys. That is why the evaluation of CONSTRUCT changes in these cases and needs a small adaptation.
```suggestion
    // Forward chaining inference uses CONSTRUCT internally. In this case the number of quads in the BGP is very large
    // and the number of rows in the Multiset is very small. This is an unusual case compared to the use of CONSTRUCT
    // in normal queries. That is why the evaluation of CONSTRUCT changes in these cases and needs a small adaptation.
```

2022-07-28 21:41 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +      })
```suggestion
      .flatMap {
        case Construct(bgp, _) => bgp.quads
      }
```

2022-07-29 16:09 UTC, L-Lavigne requested changes
One more suggestion, for the new forward-chaining detection logic.

2022-07-29 16:09 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +      .reduce(_ && _)
For performance reasons we should use a `Set` instead of a `List` when calling `contains`. (Also, there's some typos in val/def names in this section.)

```suggestion
    val forwardChainingQuads: Set[Expr] =
      forwardChainingOWLAxiomsAndRDFSEntailments
        .flatMap { case Construct(bgp, _) =>
          bgp.quads
        }.toSet

    val usingForwardChaining: Boolean = bgp.quads
      .map(forwardChainingQuads.contains)
      .reduce(_ && _)
```

2022-08-01 16:25 UTC, L-Lavigne reviewed
Looks good, just one typo remaining, and I have a question about a test setting.

2022-08-01 16:25 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +      forwardChainigOWLAxiomnsAndRDFSEntailments.flatMap {
```suggestion
      forwardChainingOWLAxiomsAndRDFSEntailments.flatMap {
```

2022-08-01 16:25 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/inference/ForwardChainingInference.scala
> +  val forwardChainigOWLAxiomnsAndRDFSEntailments = List(
```suggestion
  val forwardChainingOWLAxiomsAndRDFSEntailments: List[DAG[Fix[DAG]]] = List(
```

2022-08-01 16:25 UTC, L-Lavigne commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/SparkSpec.scala
> +      .set("spark.ui.enabled", "true")
Just curious, why this change? I'm not familiar with that option but it sounds like we wouldn't want any UI for unit testing.

2022-08-03 11:16 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/SparkSpec.scala
> +      .set("spark.ui.enabled", "true")
Yes, that's right. I needed to check the Spark SQL DAG for some unit test locally. 
I don't know the reason why it is not enabled. It could be because it affects performance. I'm going to change it to false just in case.

2022-08-03 17:16 UTC, L-Lavigne approved these changes

2022-08-04 17:40 UTC, merged