Join DataFrames of the quads, with the DataFrame of the clause VALUE with commons bindings, before join between them.
gsk-aiops/bellman pull request #748
Opened 2022-08-04 09:25 UTC by TomyMeren

The current behaviour with the VALUES clause is to join the DataFrame it generates, at the end of the process. This causes us to work with a lot of unnecessary data throughout the whole process and only remove it at the end.

With this approach we try to reduce the number of rows from the beginning, in the DataFrames of the quads with common binding to the VALUES DataFrame. 

## Type of change

Make sure you add the correct label for the PR:

- `breaking-change` if this PR introduces a breaking change
- `enhancement` if it adds a new feature
- `bug` if it fixes a bug
- `test` if it adds or updates tests
- `documentation` if it adds or updates documentation
- `dependency-update` if it updates dependencies

2022-08-09 16:46 UTC, L-Lavigne reviewed
Looks good, just one syntax clarity suggestion.

2022-08-09 16:49 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/JoinValues.scala
> +          "Optimizer(JoinBGPs)",
```suggestion
          "Optimizer(JoinValues)",
```

2022-08-15 06:19 UTC, L-Lavigne reviewed
I made a suggestion to reduce collection traversals a bit.

Also I had a question about the name of this optimization.

2022-08-15 06:19 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardValues.scala
> +              )
```suggestion
        // try to join the table with the quads whenever they have common variables.
        case Quad(s, p, o, _) =>
          val spo = Set(s, p, o)
          val commonValues = tableVars.filter(spo)
          if (commonValues.isEmpty) {
            quad
          } else if (commonValues.size == tableVars.size) {
            T.algebra(Join(quad, T.algebra(Table(tableVars, tableRows))))
          } else {
            val commonsSet = commonValues.toSet
            // join only with the common and defined values
            val onlyCommonRows = tableRows
              .map(row => Row(row.tuples.filter(t => commonsSet.contains(t._1))))
              .filter(_.tuples.nonEmpty)
            if(onlyCommonRows.size == tableRows.size) {
              T.algebra(Join(quad, T.algebra(Table(commonValues, onlyCommonRows))))
```

2022-08-15 06:19 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardValues.scala
> +          "Optimizer(JoinValues)",
What is the meaning of "Moving Forward" in this context? It seems unclear.

```suggestion
          "Optimizer(MovingForwardValues)",
```

2022-08-22 10:16 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardValues.scala
> +          "Optimizer(JoinValues)",
This change applies the join between the different quads and the table generated by the values VALUE clause, with common columns, instead of doing the join only once at the end of the process. The idea is to remove unwanted data as soon as possible. 

So it is a way to forward (and also distribute) the joins with the table generated in the VALUE clause in the DAG.

Perhaps a more convenient name could be advanceJoinValueClause

2022-08-23 07:10 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardValues.scala
> +          "Optimizer(JoinValues)",
So by "forward", do you mean "forward in time", as in "earlier"? If so, I think a name like "EarlyJoinOnValueClause" would be more clear. Please make sure to update the name in the debug statement also.

2022-09-14 14:21 UTC, vil1 commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +        case _ => Nil
Is this for removing the warning about pattern-matching exhaustiveness checking?

2022-09-14 14:31 UTC, vil1 commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +      dataframe = broadcast(df)
I can't work out why this `broadcast` is useful here (bu I'm not very good at spark)

2022-09-14 14:31 UTC, vil1 commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/EarlyJoinOnValue.scala
> +object EarlyJoinOnValue {
Since we already have `PushDownBGPs`, maybe we could name this `PushDownJoins` or `PushDownJoinOnValue`?

2022-09-14 15:06 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +        case _ => Nil
Yes, it is true that it is not related to this PR.  I can separate it into another PR

2022-09-14 15:13 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +      dataframe = broadcast(df)
Broadcast sends a copy of the DataFrame to all nodes in the cluster to join the data separately. This greatly improves performance when we join two DataFrames, one large and one small, and apply bradcast to the small one. Especially in parallelism.

In this case the table generated in the VALUES clause is created manually in the query so we can say that it will always be smaller than the input DataFrame.

Translated with www.DeepL.com/Translator (free version)

2022-09-14 15:17 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/EarlyJoinOnValue.scala
> +object EarlyJoinOnValue {
PushDownJoinOnValue sounds good, @L-Lavigne what do you think?

2022-09-14 15:35 UTC, vil1 commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/EarlyJoinOnValue.scala
> +      if (
I think it would be better to put this check directly in the `phase` (and therefore we wouldn't need the `config` parameter here anymore)

2022-09-14 15:37 UTC, vil1 commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ValuesSpec.scala
> -
It isn't clear to me why this test isn't needed anymore

2022-09-14 15:37 UTC, vil1 requested changes
Looks good overall, but with minor comments nonetheless

2022-09-15 08:38 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/EarlyJoinOnValue.scala
> +object EarlyJoinOnValue {
I'm not very familiar with the Spark "push down" concept and whether it's the correct name for our optimizations, but if it is, then I'm OK with using the name here and also in https://github.com/gsk-aiops/bellman/pull/759.

2022-09-15 08:44 UTC, L-Lavigne reviewed
Looks good, just some typos in tests.

2022-09-15 08:44 UTC, L-Lavigne commented on modules/engine/src/test/scala/com/gsk/kg/engine/optimizer/EarlyJoinOnValueSpec.scala
> +      "using a two variable in the clause, one appearing in a single quad and the other in more than one quad" in {
```suggestion
      "using two variables in the clause, one appearing in a single quad and the other in more than one quad" in {
```
(same applies to other tests with similar descriptions)

2022-09-15 13:43 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ValuesSpec.scala
> -
I have added a new test and removed two that were repeated.

2022-09-15 13:49 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/EarlyJoinOnValue.scala
> +object EarlyJoinOnValue {
It is not a spark concept, if anything by Jena Fuseki, but in any case the important thing is that it is understood.
The other PR is already merged so I'll keep the name and change it later, with other little things in a new PR.

2022-09-15 13:50 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/EarlyJoinOnValue.scala
> +      if (
Done!

2022-09-15 14:54 UTC, vil1 commented on modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
> +        case _ => Nil
I think it can remain there, my question was just out of curiosity

2022-09-15 18:10 UTC, TomyMeren commented
I have made a general re-naming of part of the optimised ones and removed the apply to phase setting in the two new optimised ones.

2022-09-15 18:14 UTC, L-Lavigne requested changes

2022-09-15 18:14 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/PushDownJoinOnValue.scala
> +  def phase[T](implicit T: Basis[DAG, T]): Phase[T, T] = {
This function looks like a copy of the one in PushDownFilter. Can we refactor those two into one?

2022-09-15 18:14 UTC, L-Lavigne commented on modules/engine/src/test/scala/com/gsk/kg/engine/optimizer/PushDownJoinOnValueSpec.scala
> +      "using a two variable in the clause, one with undefined values, one appearing in a single quad and the other in more than one quad" in {
```suggestion
      "using two variables in the clause, one with undefined values, one appearing in a single quad and the other in more than one quad" in {
```
Again, this applies to all similar test descriptions.

2022-09-16 10:04 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/optimizer/PushDownJoinOnValueSpec.scala
> +      "using a two variable in the clause, one with undefined values, one appearing in a single quad and the other in more than one quad" in {
Fixed in two other places

2022-09-19 15:32 UTC, L-Lavigne requested changes

2022-09-19 15:35 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/PushDownJoinOnValue.scala
> +  def phase[T](implicit T: Basis[DAG, T]): Phase[T, T] = {
I’ve done a refactor. Let me know if it ’s correct

2022-09-19 15:44 UTC, TomyMeren commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/Optimizer.scala
> +            result.pure[M]
Done!

2022-09-19 15:51 UTC, L-Lavigne reviewed
Almost there, just some typos left in test descriptions

2022-09-19 15:51 UTC, L-Lavigne commented on modules/engine/src/test/scala/com/gsk/kg/engine/optimizer/PushDownJoinOnValueSpec.scala
> +      "using a two variable in the clause, the both with undefined values, one appearing in a single quad and the other in more than one quad" in {
```suggestion
      "using two variables in the clause, both with undefined values, one appearing in a single quad and the other in more than one quad" in {
```

2022-09-19 15:51 UTC, L-Lavigne commented on modules/engine/src/test/scala/com/gsk/kg/engine/optimizer/PushDownJoinOnValueSpec.scala
> +      "using a two variable in the clause, the both with defined and undefined values, one appearing in a single quad and the other in more than one quad" in {
```suggestion
      "using two variables in the clause, both with defined and undefined values, one appearing in a single quad and the other in more than one quad" in {
```

2022-09-19 18:36 UTC, L-Lavigne approved these changes

2022-09-21 07:18 UTC, vil1 approved these changes

2022-09-21 11:57 UTC, merged