Filter improved perfomance
gsk-aiops/bellman pull request #759
Opened 2022-09-06 14:54 UTC by TomyMeren

# Description

New Optimisation step. This optimisation applies the filters to the individual quads in order to move the filters forward in the DAG and remove unused data as early as possible. 
For this all filter variables have to be declared in the quad. In case the filter cannot be applied to any of the individual quads, it will be applied to the BGP with all the variables at the end of the process, as the non-optimised tree.
Ex:
Original GAP
Filter(BGP(quad1_title, quad2_price, quad3_author), graterThan(price, 20))

Optimised GAP
BGP(quad1_title, Filter(quad2_price, graterThan(price, 20)), quad3_author)

A next step, pending to implement, could be to apply the filters to a group of quads (BGPs), without breaking the order of the quads, when we have related enough of them to complicate the filter rather than waiting to have them all related at the end.
Ex
Original GAP
Filter(BGP(quad1_title, quad2_author, quad3_price, quad4_priceWithDiscount), equal(price, priceWithDiscount ))

Optimised GAP 
BGP(quad1_title, quad2_author, Filter(BGP(quad3_price, quad4_priceWithDiscount), equal(price, priceWithDiscount )))

## Type of change

Make sure you add the correct label for the PR:

- `breaking-change` if this PR introduces a breaking change
- `enhancement` if it adds a new feature
- `bug` if it fixes a bug
- `test` if it adds or updates tests
- `documentation` if it adds or updates documentation
- `dependency-update` if it updates dependencies

2022-09-07 01:22 UTC, L-Lavigne requested changes
Good work, please see my suggestions and questions.

Also the same applies as my comment in the other "moving forward" PR (https://github.com/gsk-aiops/bellman/pull/748#discussion_r952231115), I think we could use a clearer name.

2022-09-07 01:22 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardFilter.scala
> +  * of the process, as the non-optimised tree.
```suggestion
 * This optimization applies `Filter`s to the individual quads in order to move the filters forward in the DAG and
  * remove unused data as early as possible. For this all filter variables have to be declared in the quad.
  * In case the filter cannot be applied to any of the individual quads, it will be applied to the BGP at the end
  * of the process, as the non-optimized path.
```

2022-09-07 01:22 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardFilter.scala
> +    FilteredQuadResult(filteredQuad, filterStatusLists.notApplicable)
```suggestion
  def calculateFilteredQuads[T](q: T, filters: NonEmptyList[Expression])(implicit T: Basis[DAG, T]): FilteredQuadResult[T] = {
    val filtersWithChildrenOfAND = filters.flatMap(withChildrenOfAND)
    val (applicableFilters, nonApplicableFilters) =
      filtersWithChildrenOfAND.toList.partition(calculateFilterStatus(q, _) == FilterStatus.Applicable)
    val filteredQuad = NonEmptyList
      .fromList(applicableFilters)
      .fold(q)(filters => T.algebra(Filter(filters, q)))
    FilteredQuadResult(filteredQuad, nonApplicableFilters)
  }
```

2022-09-07 01:22 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardFilter.scala
> +      case AND(l, r) => andToList(NonEmptyList.one(l)) ::: andToList(NonEmptyList.one(r))
```suggestion
  //The AND logical operator is the only Expression that can optimized even if it contains variables of different quads,
  //because we can split the two child expressions in two elements of the filter list without changing behaviour
  def withChildrenOfAND(filter: Expression): NonEmptyList[Expression] = {
    filter match {
      case AND(l, r) => withChildrenOfAND(l) ::: withChildrenOfAND(r)
```

2022-09-07 01:22 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardFilter.scala
> +        if (filterVariables.size == variablesInQuad.size) {
```suggestion
      case Quad(s, p, o, _) =>
        val spo = Set(s, p, o)
        if (findVariablesIn(f).forall(spo.contains)) {
```

2022-09-07 01:22 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/MovingForwardFilter.scala
> +  def calculateFilterVariables(f: Expression): List[StringVal.VARIABLE] = f.getInnerStringValList.collect {
```suggestion
  //Recursively traverse the children of the expression looking for Variables
  def findVariablesIn(f: Expression): List[StringVal.VARIABLE] = f.getInnerStringValList.collect {
```

2022-09-07 01:22 UTC, L-Lavigne commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/SparkSpec.scala
> +      .set("spark.ui.enabled", "true")
Looks like this got changed again by mistake

2022-09-07 01:22 UTC, L-Lavigne commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/FilterSpec.scala
> +        result.right.get.collect//.length shouldEqual 2
Was this left commented out by accident? We should be looking at the contents of the result.

2022-09-07 01:22 UTC, L-Lavigne commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/FilterSpec.scala
> +        //Thread.sleep(300000)
This can be removed

2022-09-07 01:22 UTC, L-Lavigne commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
> +  def getInnerStringValList:List[StringVal]
```suggestion
  def getInnerStringValList: List[StringVal]
```

2022-09-07 01:22 UTC, L-Lavigne commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
> +  def getInnerStringValList:List[StringVal]
Is this method expected to be called more than once for a given `Expression` instance? If so, I suggest making the implementations `lazy val`s instead of `def`s.

2022-09-08 08:46 UTC, TomyMeren commented on modules/engine/src/test/scala/com/gsk/kg/engine/compiler/FilterSpec.scala
> +        result.right.get.collect//.length shouldEqual 2
Yes... my bad

2022-09-08 15:03 UTC, L-Lavigne commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
> +  def getInnerStringValList:List[StringVal]
Yes, exactly 👍

2022-09-12 15:34 UTC, TomyMeren commented on modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
> +  def getInnerStringValList:List[StringVal]
Changed

2022-09-13 15:59 UTC, L-Lavigne requested changes
Looks good, just one more change to make, to memoize a computation result.

2022-09-13 15:59 UTC, L-Lavigne commented on modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/EarlyFilter.scala
> +        !findVariablesIn(f).isEmpty && findVariablesIn(f).forall(spo.contains)
```suggestion
      val variables = findVariablesIn(f)
      if (
        variables.nonEmpty && variables.forall(spo.contains)
```

2022-09-15 08:32 UTC, L-Lavigne approved these changes

2022-09-15 12:17 UTC, merged